version: "3.9"

networks:
  network:
    external: true
    name: network

services:
  gitlab:
    container_name: gitlab
    hostname: gitlab.local.com
    image: gitlab/gitlab-ee:latest
    networks:
      - network
    volumes:
      - ./config/gitlab/gitlab_config:/etc/gitlab
      - ./config/gitlab/gitlab_logs:/var/log/gitlab
      - ./config/gitlab/gitlab_data:/var/opt/gitlab
    ports:
      - "443:443"
      - "80:80"
      - "2222:22"
    restart: unless-stopped

  docker-deamon:
    container_name: docker-deamon
    image: docker:dind
    privileged: true
    command: dockerd --host=tcp://0.0.0.0:2375 --host=unix:///var/run/docker.sock
    # environment:
    #   - DOCKER_TLS_CERTDIR=/certs
    # volumes:
    #   - ./config/certs/some-docker-certs-ca:/certs/ca
    #   - ./config/certs/some-docker-certs-client:/certs/client
    networks:
      - network
    restart: unless-stopped

  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    volumes:
      - ./config/runner/config:/etc/gitlab-runner
    #   - ./config/certs/some-docker-certs-client:/certs/client:ro
    # environment:
    #   - DOCKER_TLS_CERTDIR=/certs
    networks:
      - network
    restart: unless-stopped

# if using tls
# in config.toml tls_verify=true and host = "tcp://docker-deamon:2376/" and use network alias docker for the docker-deamon container